[project]
name = "sklearn-repo-status"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "matplotlib>=3.10.3",
    "pygithub>=2.6.1",
]
