name: Build webpage

on:
  schedule:
    # Nightly build at 23:00
    - cron: "0 23 * * * "
  push:
    branches:
      - main
  # Manual run
  workflow_dispatch:

jobs:
  build_webpage:
    name: Build webpage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: x64
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/cache@v2
        with:
          path: ~/.cache/ghcache.json
          key: ${{ runner.os }}-ghcache-v2-${{ hashFiles('make.py') }}
          restore-keys: |
            ${{ runner.os }}-ghcache-v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run builder
        run: |
          python make.py ~/.cache/ghcache.json dist --repo scikit-learn/scikit-learn
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
